// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif
void start_can(lv_event_t * e);
void stop_can(lv_event_t * e);
void brightness_inc(lv_event_t * e);
void brightness_dec(lv_event_t * e);
void clear_frame(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
