// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project
#include "Arduino.h"
#include "skp_lcd.h"
#include "ui.h"

uint8_t buff[20];
extern uint8_t brightness;
extern uint8_t can_start;
extern uint32_t frame_count;

	// Your code here}
void brightness_inc(lv_event_t * e)
{
	brightness = brightness + 5;
	set_brightness();
}


void brightness_dec(lv_event_t * e)
{
	brightness = brightness - 5;
	set_brightness();
}

void stop_can(lv_event_t * e)
{
	can_start = 0;
}
void start_can(lv_event_t * e)
{
		can_start = 1;
}




void clear_frame(lv_event_t * e)
{
	frame_count = 0;
}
