// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void brightness_inc(lv_event_t * e)
{
	// Your code here
}

void brightness_dec(lv_event_t * e)
{
	// Your code here
}

void stop_can(lv_event_t * e)
{
	// Your code here
}

void clear_frame(lv_event_t * e)
{
	// Your code here
}

void start_can(lv_event_t * e)
{
	// Your code here
}
