// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Slider1;
extern lv_obj_t *ui_Switch1;
extern lv_obj_t *ui_Button3;
extern void ui_event_Button4( lv_event_t * e);
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_Spinner1;
extern lv_obj_t *ui_Label2;
extern void ui_event_Button5( lv_event_t * e);
extern lv_obj_t *ui_Button5;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Label9;
extern void ui_event_Button6( lv_event_t * e);
extern lv_obj_t *ui_Button6;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_Label18;
extern lv_obj_t *ui_Label19;
extern lv_obj_t *ui_Label20;
extern lv_obj_t *ui_Label21;
extern lv_obj_t *ui_Label22;
extern lv_obj_t *ui_Label23;
// CUSTOM VARIABLES
extern lv_obj_t *uic_canFDdata;
extern lv_obj_t *uic_ccCANdata;
extern lv_obj_t *uic_canfdID;
extern lv_obj_t *uic_canFDLen;
extern lv_obj_t *uic_ccanID;
extern lv_obj_t *uic_ccanLen;
extern lv_obj_t *uic_frameCount;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

