// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_frameCount;
lv_obj_t *uic_ccanLen;
lv_obj_t *uic_ccanID;
lv_obj_t *uic_canFDLen;
lv_obj_t *uic_canfdID;
lv_obj_t *uic_ccCANdata;
lv_obj_t *uic_canFDdata;
lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Button1 = NULL;lv_obj_t *ui_Button2 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_Slider1 = NULL;lv_obj_t *ui_Switch1 = NULL;lv_obj_t *ui_Button3 = NULL;lv_obj_t *ui_Button4 = NULL;lv_obj_t *ui_Spinner1 = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_Button5 = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_Label8 = NULL;lv_obj_t *ui_Label9 = NULL;lv_obj_t *ui_Button6 = NULL;lv_obj_t *ui_Label10 = NULL;lv_obj_t *ui_Panel1 = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_Label11 = NULL;lv_obj_t *ui_Label12 = NULL;lv_obj_t *ui_Panel2 = NULL;lv_obj_t *ui_Panel3 = NULL;lv_obj_t *ui_Label13 = NULL;lv_obj_t *ui_Label14 = NULL;lv_obj_t *ui_Label15 = NULL;lv_obj_t *ui_Label16 = NULL;lv_obj_t *ui_Label17 = NULL;lv_obj_t *ui_Label18 = NULL;lv_obj_t *ui_Label19 = NULL;lv_obj_t *ui_Label20 = NULL;lv_obj_t *ui_Label21 = NULL;lv_obj_t *ui_Label22 = NULL;lv_obj_t *ui_Label23 = NULL;
// event funtions
void ui_event_Button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      stop_can( e );
}
}

void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      start_can( e );
}
}

void ui_event_Button4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      brightness_inc( e );
}
}

void ui_event_Button5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      brightness_dec( e );
}
}

void ui_event_Button6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      clear_frame( e );
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button1 = lv_button_create(ui_Screen1);
lv_obj_set_width( ui_Button1, 100);
lv_obj_set_height( ui_Button1, 50);
lv_obj_set_x( ui_Button1, 197 );
lv_obj_set_y( ui_Button1, 571 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button2 = lv_button_create(ui_Screen1);
lv_obj_set_width( ui_Button2, 100);
lv_obj_set_height( ui_Button2, 50);
lv_obj_set_x( ui_Button2, 303 );
lv_obj_set_y( ui_Button2, 571 );
lv_obj_set_align( ui_Button2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor(ui_Button2, lv_color_hex(0x0000FF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_recolor_opa(ui_Button2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -2 );
lv_obj_set_y( ui_Label1, -552 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"10.1\" LCD 800x1280");
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Slider1 = lv_slider_create(ui_Screen1);
lv_slider_set_value( ui_Slider1, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider1)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider1, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider1, 522);
lv_obj_set_height( ui_Slider1, 51);
lv_obj_set_x( ui_Slider1, 73 );
lv_obj_set_y( ui_Slider1, 409 );
lv_obj_set_align( ui_Slider1, LV_ALIGN_CENTER );

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_Slider1,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_Slider1, lv_obj_get_style_pad_right(ui_Slider1,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_Switch1 = lv_switch_create(ui_Screen1);
lv_obj_set_width( ui_Switch1, 81);
lv_obj_set_height( ui_Switch1, 44);
lv_obj_set_x( ui_Switch1, -327 );
lv_obj_set_y( ui_Switch1, 418 );
lv_obj_set_align( ui_Switch1, LV_ALIGN_CENTER );

ui_Button3 = lv_button_create(ui_Screen1);
lv_obj_set_width( ui_Button3, 100);
lv_obj_set_height( ui_Button3, 50);
lv_obj_set_x( ui_Button3, 91 );
lv_obj_set_y( ui_Button3, 571 );
lv_obj_set_align( ui_Button3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button4 = lv_button_create(ui_Screen1);
lv_obj_set_width( ui_Button4, 100);
lv_obj_set_height( ui_Button4, 50);
lv_obj_set_x( ui_Button4, -212 );
lv_obj_set_y( ui_Button4, 579 );
lv_obj_set_align( ui_Button4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Spinner1 = lv_spinner_create(ui_Screen1);
//lv_spinner_set_anim_params(ui_Spinner1, 1000, 90);
lv_obj_set_width( ui_Spinner1, 138);
lv_obj_set_height( ui_Spinner1, 153);
lv_obj_set_x( ui_Spinner1, -295 );
lv_obj_set_y( ui_Spinner1, -502 );
lv_obj_set_align( ui_Spinner1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Spinner1, LV_OBJ_FLAG_CLICKABLE );    /// Flags

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -10 );
lv_obj_set_y( ui_Label2, -485 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"skpang.co.uk 09/2025");
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button5 = lv_button_create(ui_Screen1);
lv_obj_set_width( ui_Button5, 100);
lv_obj_set_height( ui_Button5, 50);
lv_obj_set_x( ui_Button5, -325 );
lv_obj_set_y( ui_Button5, 579 );
lv_obj_set_align( ui_Button5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -213 );
lv_obj_set_y( ui_Label3, 580 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"+");
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, -330 );
lv_obj_set_y( ui_Label4, 577 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"-");
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, -277 );
lv_obj_set_y( ui_Label5, 533 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Brightness");

ui_Label8 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, 196 );
lv_obj_set_y( ui_Label8, 573 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"STOP");

ui_Label9 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, 301 );
lv_obj_set_y( ui_Label9, 571 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"START");

ui_Button6 = lv_button_create(ui_Screen1);
lv_obj_set_width( ui_Button6, 100);
lv_obj_set_height( ui_Button6, 50);
lv_obj_set_x( ui_Button6, -16 );
lv_obj_set_y( ui_Button6, 571 );
lv_obj_set_align( ui_Button6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0xE2FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label10 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, -16 );
lv_obj_set_y( ui_Label10, 574 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"CLEAR");

ui_Panel1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel1, 744);
lv_obj_set_height( ui_Panel1, 127);
lv_obj_set_x( ui_Panel1, -5 );
lv_obj_set_y( ui_Panel1, -336 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label6 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, -317 );
lv_obj_set_y( ui_Label6, -376 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"CAN FD (J5) :");

ui_Label7 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -348 );
lv_obj_set_y( ui_Label7, -350 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"ID : ");

ui_Label11 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label11, -344 );
lv_obj_set_y( ui_Label11, -324 );
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"Len : ");

ui_Label12 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label12, 612);
lv_obj_set_height( ui_Label12, 55);
lv_obj_set_x( ui_Label12, 42 );
lv_obj_set_y( ui_Label12, -355 );
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"00");

ui_Panel2 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel2, 744);
lv_obj_set_height( ui_Panel2, 113);
lv_obj_set_x( ui_Panel2, -8 );
lv_obj_set_y( ui_Panel2, -198 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel3 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel3, 744);
lv_obj_set_height( ui_Panel3, 113);
lv_obj_set_x( ui_Panel3, -8 );
lv_obj_set_y( ui_Panel3, -64 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label13 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label13, -302 );
lv_obj_set_y( ui_Label13, -232 );
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"Classic CAN (J3) :");

ui_Label14 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label14, 443);
lv_obj_set_height( ui_Label14, 22);
lv_obj_set_x( ui_Label14, -14 );
lv_obj_set_y( ui_Label14, -228 );
lv_obj_set_align( ui_Label14, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label14,"00");

ui_Label15 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label15, -347 );
lv_obj_set_y( ui_Label15, -211 );
lv_obj_set_align( ui_Label15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label15,"ID : ");

ui_Label16 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label16, -340 );
lv_obj_set_y( ui_Label16, -188 );
lv_obj_set_align( ui_Label16, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label16,"Len : ");

ui_Label17 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label17, -328 );
lv_obj_set_y( ui_Label17, -98 );
lv_obj_set_align( ui_Label17, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label17,"Transmit");

ui_Label18 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label18, -307 );
lv_obj_set_y( ui_Label18, -73 );
lv_obj_set_align( ui_Label18, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label18,"Frame count : ");

ui_Label19 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label19, 74);
lv_obj_set_height( ui_Label19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label19, 68 );
lv_obj_set_y( ui_Label19, -348 );
lv_obj_set_align( ui_Label19, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label19,"0");
lv_obj_set_style_text_align(ui_Label19, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label20 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label20, 74);
lv_obj_set_height( ui_Label20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label20, 78 );
lv_obj_set_y( ui_Label20, -324 );
lv_obj_set_align( ui_Label20, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label20,"0");
lv_obj_set_style_text_align(ui_Label20, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label21 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label21, 74);
lv_obj_set_height( ui_Label21, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label21, 72 );
lv_obj_set_y( ui_Label21, -209 );
lv_obj_set_align( ui_Label21, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label21,"0");
lv_obj_set_style_text_align(ui_Label21, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label22 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label22, 74);
lv_obj_set_height( ui_Label22, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label22, 82 );
lv_obj_set_y( ui_Label22, -187 );
lv_obj_set_align( ui_Label22, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label22,"0");
lv_obj_set_style_text_align(ui_Label22, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label23 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label23, 74);
lv_obj_set_height( ui_Label23, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label23, 148 );
lv_obj_set_y( ui_Label23, -72 );
lv_obj_set_align( ui_Label23, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label23,"0");
lv_obj_set_style_text_align(ui_Label23, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
uic_canFDdata = ui_Label12;
uic_ccCANdata = ui_Label14;
uic_canfdID = ui_Label19;
uic_canFDLen = ui_Label20;
uic_ccanID = ui_Label21;
uic_ccanLen = ui_Label22;
uic_frameCount = ui_Label23;

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Button1= NULL;
ui_Button2= NULL;
ui_Label1= NULL;
ui_Slider1= NULL;
ui_Switch1= NULL;
ui_Button3= NULL;
ui_Button4= NULL;
ui_Spinner1= NULL;
ui_Label2= NULL;
ui_Button5= NULL;
ui_Label3= NULL;
ui_Label4= NULL;
ui_Label5= NULL;
ui_Label8= NULL;
ui_Label9= NULL;
ui_Button6= NULL;
ui_Label10= NULL;
ui_Panel1= NULL;
ui_Label6= NULL;
ui_Label7= NULL;
ui_Label11= NULL;
uic_canFDdata= NULL;
ui_Label12= NULL;
ui_Panel2= NULL;
ui_Panel3= NULL;
ui_Label13= NULL;
uic_ccCANdata= NULL;
ui_Label14= NULL;
ui_Label15= NULL;
ui_Label16= NULL;
ui_Label17= NULL;
ui_Label18= NULL;
uic_canfdID= NULL;
ui_Label19= NULL;
uic_canFDLen= NULL;
ui_Label20= NULL;
uic_ccanID= NULL;
ui_Label21= NULL;
uic_ccanLen= NULL;
ui_Label22= NULL;
uic_frameCount= NULL;
ui_Label23= NULL;

}
